# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy CD

on:
  push:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest]
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@arsamsarabi"
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
