# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy CD

on:
  push:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest]
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn lint

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-to-publish
          path: |
            build
            package.json
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: build-test-lint

    steps:
      - name: Download publish artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts-to-publish
      - run: npm publish
