# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@main
        with:
          name: build artifacts
          path: public/

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, and test
        run: |
          yarn
          yarn test
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, and test
        run: |
          yarn
          yarn lint
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download built artifact
        uses: actions/download-artifact@main
        with:
          name: build artifacts
          path: public
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GH_PUBLISHER}}
          registry: docker.pkg.github.com
          repository: arsamsarabi/arsam-component-library
          tag_with_sha: true
