name: Build and Deploy CD

on:
  push:
    branches: [main]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: yarn

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: yarn build
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     path: build

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: yarn lint

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, lint]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@arsamsarabi"
      # - name: Download publish artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
