name: Deploy CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          registry-url: "https://registry.npmjs.org"
          always-auth: true
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - run: yarn
      - run: yarn build
      - run: yarn pack
      - run: yarn publish arsamsarabi-arsam-component-library-v${{steps.package-version.outputs.current-version}}.tgz  --access public
