name: Verify and Deploy CD

on:
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: yarn
      - run: yarn test
      - run: yarn lint
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@arsamsarabi"
      - name: Download publish artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
